# Generated by Django 3.2.13 on 2022-04-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='write text', verbose_name='text comment')),
                ('image', models.ImageField(blank=True, upload_to='tickets/', verbose_name='image')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='comment creation date')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ticket name')),
                ('text', models.TextField(help_text='write text', verbose_name='ticket text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tickets/', verbose_name='image')),
                ('status', models.CharField(choices=[('active', 'Active'), ('complite', 'Complite'), ('frozen', 'Frozen')], default='active', max_length=20, verbose_name='ticket status')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='ticket creation date')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-pub_date'],
            },
        ),
    ]
