# Generated by Django 2.2.16 on 2022-04-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Напишите комментарий', verbose_name='текст комментария')),
                ('image', models.ImageField(blank=True, upload_to='tickets/', verbose_name='Картинка')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='имя тикета')),
                ('text', models.TextField(help_text='Напишите текст', verbose_name='текст тикета')),
                ('image', models.ImageField(blank=True, upload_to='tickets/', verbose_name='Картинка')),
                ('status', models.CharField(choices=[('active', 'active'), ('complite', 'complite'), ('frozen', 'frozen')], default='active', max_length=20, verbose_name='статус тикета')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания тикета')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['-pub_date'],
            },
        ),
    ]
